name: testRigor Automation Pipeline

on:
  push:
    branches:
      - main

jobs:
  execute-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trigger testRigor Suite
        run: |
          curl -X POST \
          "https://api.testrigor.com/api/v1/apps/YOUR_APP_ID/suites/YOUR_SUITE_ID/run" \
          -H "Authorization: Token YOUR_API_TOKEN"
